# Generated by Django 3.1.5 on 2021-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='Blog_Photos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='vid',
            field=models.FileField(null=True, upload_to='Blog_Videos/', verbose_name=''),
        ),
    ]
