# Generated by Django 3.1.5 on 2021-03-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210323_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
