# Generated by Django 3.1.5 on 2021-03-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vid',
            field=models.FileField(default='default.mp4', upload_to='videos/'),
        ),
    ]
