# Generated by Django 3.1.5 on 2021-03-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vid',
            field=models.FileField(default='default.mp4', upload_to='videos/'),
        ),
    ]
